kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-monitoring-ns
  namespace: kube-system
subjects:
  - kind: Group
    name: groupDEV
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-kube-system
  apiGroup: rbac.authorization.k8s.io

