apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: kube-system
  labels:
    k8s-app: journalbeat-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: journalbeat-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: journalbeat-logging
        version: v1
        app: journalbeat
        name: journalbeat
    spec:
      containers:
        - args:
            - -e
            - -c
            - /etc/journalbeat.yml
          command:
            - journalbeat
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOGSTASH_HOSTS
              value: logstash-host.domain.com
            - name: LOGSTASH_PORT
              value: "5044"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
            - name: ENVIRONMENT
              value: dev

          image: docker.elastic.co/beats/journalbeat:7.8.0
          imagePullPolicy: Always
          name: journalbeat
          resources:
            limits:
              cpu: 600m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 400Mi
          volumeMounts:
            - mountPath: /usr/share/journalbeat/data
              name: data
            - mountPath: /var/log/journal
              name: var-journal
            - mountPath: /run/log/journal
              name: run-journal
            - mountPath: /etc/journalbeat.yml
              name: config
              subPath: journalbeat.yml
            - mountPath: /etc/machine-id
              name: machine-id
      hostNetwork: true
      nodeSelector: {}

### required for SE Linux protected ones
      securityContext:
        seLinuxOptions:
          user: system_u
          role: system_r
          type: spc_t
          level: s0

        fsGroup: 0
        runAsUser: 0
      serviceAccountName: journalbeat
      terminationGracePeriodSeconds: 60
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /var/log/journal/journalbeat-data
          name: data
        - hostPath:
            path: /var/log/journal
          name: var-journal
        - hostPath:
            path: /run/log/journal
          name: run-journal
        - hostPath:
            path: /etc/machine-id
          name: machine-id
        - configMap:
            items:
              - key: journalbeat.yml
                path: journalbeat.yml
            name: journalbeat-config
          name: config
