version: "3.7"

services:
  caddy:
    image: caddy:2.2.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/data:/data/caddy
    networks:
      - host
volumes:
  data01:
    driver: local
networks:
  host:
