kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-dev-groupQA-R
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
