kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-monitoring-ns
  namespace: default
subjects:
  - kind: Group
    name: groupQA
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-default
  apiGroup: rbac.authorization.k8s.io

